%function abc()
clear;
close all;
clc;

syms mp1 mp2 ms1 ms2 Is1 Is2 lpend1 lpend2 R1 R2 g theta1 theta2 phi1 phi2 theta1_dot theta2_dot theta1_ddot theta2_ddot phi1_dot phi2_dot phi1_ddot phi2_ddot tau1 tau2 zeta1 zeta2 G
G % will be set to 9.8m/s^2
g = [0;-G;0];
% find out position of bottom sphere from thata2
posSphere2 = [R2*theta2;R2;0];
% find out position of pendulum from position of sphere and phi2
posPend2 = posSphere2 + lpend2*[sin(phi2);-cos(phi2);0];
% find out angle of phere 1 w.r.t vertical axis
delta = theta2+R1*(theta1)/R2;
% find out position of phere1
posSphere1 = (R2+R1)*[sin(delta);cos(delta);0] +posSphere2;
% find out position of pendulum 1
posPend1 = posSphere1 + lpend1*[sin(phi1);-cos(phi1);0];

% differentiate all position to get velocities
vs1 = diff(posSphere1,theta1)*theta1_dot + diff(posSphere1,theta2)*theta2_dot+diff(posSphere1,phi1)*phi1_dot + diff(posSphere1,phi2)*phi2_dot
vs2 = diff(posSphere2,theta1)*theta1_dot + diff(posSphere2,theta2)*theta2_dot+diff(posSphere2,phi1)*phi1_dot + diff(posSphere2,phi2)*phi2_dot
vp1 = diff(posPend1,theta1)*theta1_dot + diff(posPend1,theta2)*theta2_dot +diff(posPend1,phi1)*phi1_dot + diff(posPend1,phi2)*phi2_dot
vp2 = diff(posPend2,theta1)*theta1_dot + diff(posPend2,theta2)*theta2_dot +diff(posPend2,phi1)*phi1_dot + diff(posPend2,phi2)*phi2_dot

% get angular velocities
w1 = (theta1_dot +theta2_dot)*[0;0;-1];
w2 = theta2_dot*[0;0;-1];
% calculate kinetic energies
K1 = 1/2*ms1*(vs1.'*vs1) +  1/2*Is1*((w1.')*(w1)) + 1/2*mp1*(vp1.'*vp1)
K2 = 1/2*ms2*(vs2.'*vs2) +  1/2*Is2*(w2.'*w2) + 1/2*mp2*(vp2.'*vp2)
% calculate potential energies
P1 = mp1*g.'*posPend1+ms1*g.'*posSphere1;
P2 = mp2*(g.'*posPend2)+ms2*(g.'*posSphere2)
% get the Langrangian
Langr = K1+K2-P1-P2

% Get Dynamic equations for each variable
E1 = tau1 - zeta1*(theta1_dot+phi1_dot) == transpose(...
                                            diff(diff(Langr,theta1_dot),theta1_dot)*theta1_ddot ...
                                            +diff(diff(Langr,theta1_dot),theta2_dot)*theta2_ddot ...
                                            +diff(diff(Langr,theta1_dot),phi1_dot)*phi1_ddot ...
                                            +diff(diff(Langr,theta1_dot),phi2_dot)*phi2_ddot ...
                                            +diff(diff(Langr,theta1_dot),theta1)*theta1_dot ...
                                            +diff(diff(Langr,theta1_dot),theta2)*theta2_dot ...
                                            +diff(diff(Langr,theta1_dot),phi1)*phi1_dot ...
                                            +diff(diff(Langr,theta1_dot),phi2)*phi2_dot ...                                            
                                            -diff(Langr,theta1));
E2 = tau2 - zeta2*(theta2_dot+phi2_dot) == transpose(...
                                            diff(diff(Langr,theta2_dot),theta1_dot)*theta1_ddot ...
                                            +diff(diff(Langr,theta2_dot),theta2_dot)*theta2_ddot ...
                                            +diff(diff(Langr,theta2_dot),phi1_dot)*phi1_ddot ...
                                            +diff(diff(Langr,theta2_dot),phi2_dot)*phi2_ddot ...
                                            +diff(diff(Langr,theta2_dot),theta1)*theta1_dot ...
                                            +diff(diff(Langr,theta2_dot),theta2)*theta2_dot ...
                                            +diff(diff(Langr,theta2_dot),phi1)*phi1_dot ...
                                            +diff(diff(Langr,theta2_dot),phi2)*phi2_dot ...                                            
                                            -diff(Langr,theta2));
E3 = tau1 - zeta1*(theta1_dot+phi1_dot) == transpose(...
                                            diff(diff(Langr,phi1_dot),theta1_dot)*theta1_ddot ...
                                            +diff(diff(Langr,phi1_dot),theta2_dot)*theta2_ddot ...
                                            +diff(diff(Langr,phi1_dot),phi1_dot)*phi1_ddot ...
                                            +diff(diff(Langr,phi1_dot),phi2_dot)*phi2_ddot ...
                                            +diff(diff(Langr,phi1_dot),theta1)*theta1_dot ...
                                            +diff(diff(Langr,phi1_dot),theta2)*theta2_dot ...
                                            +diff(diff(Langr,phi1_dot),phi1)*phi1_dot ...
                                            +diff(diff(Langr,phi1_dot),phi2)*phi2_dot ...
                                            -diff(Langr,phi1))
                                        
E4 = tau2 - zeta2*(theta2_dot+phi2_dot) == transpose(...
                                            diff(diff(Langr,phi2_dot),theta1_dot)*theta1_ddot ...
                                            +diff(diff(Langr,phi2_dot),theta2_dot)*theta2_ddot ...
                                            +diff(diff(Langr,phi2_dot),phi1_dot)*phi1_ddot ...
                                            +diff(diff(Langr,phi2_dot),phi2_dot)*phi2_ddot ...
                                            +diff(diff(Langr,phi2_dot),theta1)*theta1_dot ...
                                            +diff(diff(Langr,phi2_dot),theta2)*theta2_dot ...
                                            +diff(diff(Langr,phi2_dot),phi1)*phi1_dot ...
                                            +diff(diff(Langr,phi2_dot),phi2)*phi2_dot ...
                                            -diff(Langr,phi2))   ;                                    
 

% covert the equations in to Mtrix form 
[M,CmT] = equationsToMatrix(E1,E2,E3,E4,[theta1_ddot;theta2_ddot;phi1_ddot;phi2_ddot]);
%%% [M * Q_ddot == CmT ] %%%%
%Print the matrices
display(-M) % minus, because matlab gives it negated
display(-CmT)
